name: damo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk: ^0.7.0    # 카카오 로그인
  # google_sign_in: ^5.0.7       # 구글 로그인
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0         # 구글 폰트
  transition: ^2.0.2           # 화면전환 애니메이션
  page_transition: ^2.0.0      # 화면전환 애니메이션 (로딩화면 사용)
  fluttertoast: ^8.0.8         # 토스트메시지
  google_maps_flutter: ^2.0.6  # 구글 맵
  flutter_login: ^2.2.1        # 로그인 애니메이션 
  font_awesome_flutter: ^9.1.0 # 폰트 아이콘
  like_button: ^2.0.2          # 좋아요(하트) 버튼
  # firebase_core: ^1.4.0      # 파이어 베이스 사용
  # firebase_auth: ^3.0.1      # 파이어 베이스 로그인
  # flutter_web_auth: ^0.3.0     
  animated_splash_screen: ^1.1.0 # 로딩화면 구성
  flutter_staggered_animations: ^1.0.0 # 업체이미지 애니메이션
  image_picker: ^0.8.3+2
  card_swiper: ^1.0.4

dependency_overrides:
  flutter_colorpicker: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #    - family: Schyler
  #      fonts:
  #        - asset: fonts/Schyler-Regular.ttf
  #        - asset: fonts/Schyler-Italic.ttf
  #          style: italic
  #    - family: Trajan Pro
  #      fonts:
  #        - asset: fonts/TrajanPro.ttf
  #        - asset: fonts/TrajanPro_Bold.ttf
  #          weight: 700
#  fonts:
#    - family: Noto_Serif_KR
#      fonts:
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-ExtraLight.otf
#          weight: 200
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-Light.otf
#          weight: 300
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-Regular.otf
#          weight: 400
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-Medium.otf
#          weight: 500
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-SemiBold.otf
#          weight: 600
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-Bold.otf
#          weight: 700
#        - asset: assets/font/Noto_Serif_KR/NotoSerifKR-Black.otf
#          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
