name: damo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  get: ^4.3.8                             # getX 
  kakao_flutter_sdk: ^0.8.1               # 카카오 로그인
  cupertino_icons: ^1.0.3      
  google_fonts: ^2.1.0                    # 구글 폰트
  transition: ^2.0.2                      # 화면전환 애니메이션
  # page_transition: ^2.0.0               # 화면전환 애니메이션 (로딩화면 사용)
  fluttertoast: ^8.0.8                    # 토스트메시지
  kakaomap_webview: ^0.3.0                # 카카오 맵
  font_awesome_flutter: ^9.1.0            # 폰트 아이콘
  animated_splash_screen: ^1.1.0          # 로딩화면 구성
  flutter_staggered_animations: ^1.0.0    # 업체이미지 애니메이션
  card_swiper: ^1.0.4                     # 업체 이미지 좌우로 넘김
  shared_preferences: ^2.0.8              # 자동 로그인을 위한 device DB
  #emoji_picker_flutter: ^1.0.7      # 이모지
  kpostal: ^0.3.2                         # 도로명 주소 검색
  http: ^0.13.3
  vertical_barchart: ^2.0.0+2             # 막대그래프
  simple_star_rating: ^0.0.3              # 별점
  firebase_auth: ^3.1.3
  sms_autofill: ^2.2.0
  firebase_core: ^1.7.0
  path_provider: ^2.0.5
  cached_network_image: ^3.1.0+1
  extended_image: ^5.1.3
  path: ^1.6.2
  flutter_svg: ^0.23.0+1
  # flutter_native_splash: ^1.2.4
  flutter_screenutil: ^5.0.0+2
  mask_text_input_formatter: ^2.0.0
  firebase_app_check: ^0.0.2+3
  image_picker: ^0.8.4+4
  lazy_load_scrollview: 1.3.0
  # image_crop: ^0.4.0
  dio: ^4.0.4
  timer_count_down: ^2.2.0


# dependency_overrides:
  # flutter_colorpicker: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images_svg/
    - assets/images_temp/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom font to your application, add a font section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "font" key with a
  # list giving the asset and other descriptors for the font. For
  # damoforyou:
  #    - family: Schyler
  #      font:
  #        - asset: font/Schyler-Regular.ttf
  #        - asset: font/Schyler-Italic.ttf
  #          style: italic
  #    - family: Trajan Pro
  #      font:
  #        - asset: font/TrajanPro.ttf
  #        - asset: font/TrajanPro_Bold.ttf
  #          weight: 700
  fonts:
    - family: NotoSansCJKKR
      fonts:
        - asset: assets/font/NotoSansCJKKR/NotoSansCJKKR-Black.otf
          weight: 900
        - asset: assets/font/NotoSansCJKKR/NotoSansCJKKR-Bold.otf
          weight: 700
        - asset: assets/font/NotoSansCJKKR/NotoSansCJKKR-Light.otf
          weight: 300
        - asset: assets/font/NotoSansCJKKR/NotoSansCJKKR-Medium.otf
          weight: 500
        - asset: assets/font/NotoSansCJKKR/NotoSansCJKKR-Regular.otf
          weight: 400
  #
  # For details regarding font from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "F93F5B"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/images/스플래시@3x.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true